import { Platform } from './types';

const FORBIDDEN_BUZZWORDS = [
  'passionate',
  'hardworking',
  'detail-oriented',
  'team player',
  'perfect fit',
  'excited about',
  'i always deliver on time',
  'deliver on time and within budget',
  'i came across your job',
  'i am writing to apply',
  'my name is',
  'i am a senior',
  'i am an experienced',
  'great project',
  'love this idea',
  'amazing opportunity',
];

const PLATFORM_LIMITS: Record<Platform, [number, number]> = {
  'Upwork': [180, 225],
  'Direct Email': [220, 310],
  'LinkedIn': [100, 160],
  'Agency RFP': [250, 360],
  'Other': [150, 300],
};

export function countWords(text: string): number {
  const cleaned = text.replace(/[#*_`~-]/g, ' ');
  return cleaned.trim().split(/\s+/).filter(Boolean).length;
}

export function lintProposal(proposalText: string, platform: Platform = 'Upwork'): string[] {
  const violations: string[] = [];
  const textLower = proposalText.trim().toLowerCase();
  const paragraphs = proposalText.trim().split(/\n\s*\n/);
  const firstParagraph = paragraphs[0]?.trim() || '';

  // Rule 1: Never open with "I" or name/title
  if (firstParagraph) {
    const cleanedFirst = firstParagraph.replace(/^[#*_"'\s]+/, '').trim();
    const firstWord = cleanedFirst.split(/\s+/)[0]?.toLowerCase() || '';
    if (['i', "i'm", 'i’ve', "i've", 'my'].includes(firstWord)) {
      violations.push("Violation: Proposal opens with 'I' or 'My'. Must open with client pain, sharp observation, or proof.");
    }
    if (/^(hi|hello|hey)?\s*(my name is|i am a|i'm a)/i.test(cleanedFirst)) {
      violations.push("Violation: Proposal opens with freelancer introduction. State client's problem first.");
    }
  }

  // Rule 2: Never use forbidden buzzwords
  for (const word of FORBIDDEN_BUZZWORDS) {
    const regex = new RegExp(`\\b${word}\\b`, 'i');
    if (regex.test(textLower)) {
      violations.push(`Violation: Contains forbidden buzzword or cliché phrase: '${word}'.`);
    }
  }

  // Rule 3: Never mention AI was used
  if (/(as an ai|large language model|generated by ai|chatgpt)/i.test(textLower)) {
    violations.push('Violation: Mentions AI or language model.');
  }

  // Rule 4: Never list skills as raw bullet points
  const lines = proposalText.split('\n');
  let bulletCount = 0;
  for (const line of lines) {
    const trimmed = line.trim();
    if (/^[-*•]/.test(trimmed) && trimmed.split(/\s+/).length < 6) {
      bulletCount++;
    }
  }
  if (bulletCount >= 3) {
    violations.push('Violation: Skills are listed as raw bullet points. Integrate tools naturally into approach.');
  }

  // Rule 5: Word count validation
  const [minWords, maxWords] = PLATFORM_LIMITS[platform] || [150, 300];
  const wc = countWords(proposalText);
  if (wc < minWords - 25) {
    violations.push(`Notice: Word count is ${wc} words, which is below the recommended minimum of ${minWords} for ${platform}.`);
  } else if (wc > maxWords + 25) {
    violations.push(`Notice: Word count is ${wc} words, which exceeds target maximum of ${maxWords} for ${platform}.`);
  }

  // Rule 6: Upwork specific - never mention "Upwork" inside
  if (platform === 'Upwork' && textLower.includes('upwork')) {
    violations.push("Violation: Mentions 'Upwork' inside an Upwork proposal.");
  }

  return violations;
}
